### ISSUE TITLE
Invalid path alias: @vova07/imperavi/assets

### ISSUE THREAD

**Issue by devypt** [vova07/yii2-imperavi-widget#21]
When trying to use it with ActiveForm

**Comment by vova07** [comment]
What code exactly are you using? Some example?

**Comment by devypt** [comment]
```
<?= $form->field($model, 'citation')->widget(Widget::className(), [
    'settings' => [
        'lang' => 'ar',
        'minHeight' => 200,
        'toolbarFixed'=>false,
        'pastePlainText' => true,
        'imageUpload' => Url::to(['/site/image-upload']),
        'plugins' => [
            'video'
            // 'clips',
            // 'fullscreen'
        ]
    ]
]); ?>

```

**Comment by vova07** [comment]
I've tested your code, but for me all are working good. Can you try to completely remove your `vendor` directory, and reinstall all libraries with `composer install`?

**Comment by devypt** [comment]
issue fixed after remove vendor and update composer, Thanks.

**Comment by skeeran** [comment]
i am also having the same error.. and i removed and installed it .. still same error.

**Comment by skeeran** [comment]
so.. i corrected the path like : 	public $sourcePath = '@vendor/vova07/yii2-imperavi-widget/assets';

now its working for me.

**Comment by albertborsos** [comment]
Still wrong, you need to update the Asset's sourcePath property to
`public $sourcePath = '@vendor/vova07/yii2-imperavi-widget/src/assets';`

because your `@vova07/imperavi` alias is setted nowehere

thx
